apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sidekick-clusterRoleBinding
subjects:
- kind: ServiceAccount
  name: sidekick-serviceaccount
  namespace: {{.Release.Namespace}}
roleRef:
  kind: ClusterRole
  name: sidekick
  apiGroup: rbac.authorization.k8s.io
