apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: sidekick-deployment
spec:
  selector:
    matchLabels:
      kubearmor-app: sidekick
  template:
    metadata:
      labels:
        kubearmor-app: sidekick
    spec:
      serviceAccountName: sidekick-serviceaccount
      containers:
      - name: sidekick-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        envFrom:
        - secretRef:
            name: sidekick-secret
